Persistent dismissal duration
YahnisElsts/admin-notices pull request #3
Opened 2019-02-03 04:04 UTC by benignant

Closes #2.

2019-02-03 10:35 UTC, YahnisElsts commented on AdminNotice.php
> +					$properties['dismissalDuration']
The `dismissalDuration` key might be missing, for example because the user upgraded from an older version of the library that didn't use this key. I recommend using getKey here to handle that possibility.
```suggestion
					self::getKey($properties, 'dismissalDuration', self::DISMISS_PERMANENTLY)
```

2019-02-03 10:43 UTC, YahnisElsts commented on AdminNotice.php
> +				$dismissalTime = $dismissalTime - ($this->dismissalDuration - $duration);
This seems a bit questionable since it means that the stored dismissal time isn't the *actual* dismissal time, which could mislead people looking at the variable names and database entries. However, I don't have any better ideas at this time.

2019-02-03 10:47 UTC, YahnisElsts requested changes
Looks okay overall, neds one minor change.

2019-02-03 22:23 UTC, benignant commented on AdminNotice.php
> +				$dismissalTime = $dismissalTime - ($this->dismissalDuration - $duration);
We could store both the real dismissal time and the dismissal duration?

2019-02-04 11:49 UTC, YahnisElsts commented on AdminNotice.php
> +				$dismissalTime = $dismissalTime - ($this->dismissalDuration - $duration);
Yes, that might make sense. It doesn't make much difference in terms of functionality, but I think it would make the code easier to understand and extend.

2019-02-05 03:39 UTC, benignant commented on AdminNotice.php
> +				$dismissalTime = $dismissalTime - ($this->dismissalDuration - $duration);
It's done.

2019-02-05 13:48 UTC, YahnisElsts requested changes

2019-02-05 13:48 UTC, YahnisElsts commented on AdminNotice.php
> +			$dismissal = json_decode($dismissal, true);
I believe that `json_decode` can trigger a warning if the input is invalid or not a string, so I recommend adding `@` here.
```suggestion
			$dismissal = @json_decode($dismissal, true);
```

2019-02-05 13:48 UTC, YahnisElsts commented on AdminNotice.php
> +			if ($dismissal === 1) {
Since `$dismissal` is no longer cast to `int`, it would probably be a string here and not a number.
```suggestion
			if ($dismissal === '1') {
```

2019-02-05 13:48 UTC, YahnisElsts commented on AdminNotice.php
> +			}
I recommend moving this `if () ...` block up above the `json_decode` call to reduce the chances that `json_decode` will get bad data.

2019-02-06 01:47 UTC, benignant commented on AdminNotice.php
> +			$dismissal = json_decode($dismissal, true);
I've committed an alternative.

2019-02-06 01:48 UTC, benignant commented on AdminNotice.php
> +			if ($dismissal === 1) {
`json_decode()` converts it into an integer.

2019-02-06 01:51 UTC, benignant commented on AdminNotice.php
> +			}
The string `1` is valid JSON, so this shouldn't be an issue.

2019-02-06 09:43 UTC, YahnisElsts approved these changes
Thank you for your patience. I'll merge this now.

2019-02-06 09:44 UTC, merged